/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SoftwareRestaurantesCucutaRouteImport } from './routes/software-restaurantes-cucuta'
import { Route as SoftwareParaPizzeriasRouteImport } from './routes/software-para-pizzerias'
import { Route as SoftwareParaComidasRapidasRouteImport } from './routes/software-para-comidas-rapidas'
import { Route as SoftwareParaCafeteriasRouteImport } from './routes/software-para-cafeterias'
import { Route as SoftwareParaBaresRouteImport } from './routes/software-para-bares'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SistemaPosRestaurantesRouteImport } from './routes/sistema-pos-restaurantes'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as MenuDigitalQrRouteImport } from './routes/menu-digital-qr'
import { Route as InventarioRestaurantesRouteImport } from './routes/inventario-restaurantes'
import { Route as FidelizacionRestaurantesRouteImport } from './routes/fidelizacion-restaurantes'
import { Route as FacturacionElectronicaRestaurantesRouteImport } from './routes/facturacion-electronica-restaurantes'
import { Route as AlternativaOlaclickRouteImport } from './routes/alternativa-olaclick'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantesIndexRouteImport } from './routes/restaurantes.index'
import { Route as DirectorioIndexRouteImport } from './routes/directorio.index'
import { Route as SitemapsRestaurantesDotxmlRouteImport } from './routes/sitemaps.restaurantes[.]xml'
import { Route as SitemapsPaginasDotxmlRouteImport } from './routes/sitemaps.paginas[.]xml'
import { Route as SitemapsDirectorioDotxmlRouteImport } from './routes/sitemaps.directorio[.]xml'
import { Route as RestaurantesCiudadIndexRouteImport } from './routes/restaurantes.$ciudad.index'
import { Route as DirectorioCiudadIndexRouteImport } from './routes/directorio.$ciudad.index'
import { Route as RestaurantesCiudadSlugRouteImport } from './routes/restaurantes.$ciudad.$slug'
import { Route as DirectorioCiudadCategoriaRouteImport } from './routes/directorio.$ciudad.$categoria'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRestaurantesCucutaRoute =
  SoftwareRestaurantesCucutaRouteImport.update({
    id: '/software-restaurantes-cucuta',
    path: '/software-restaurantes-cucuta',
    getParentRoute: () => rootRouteImport,
  } as any)
const SoftwareParaPizzeriasRoute = SoftwareParaPizzeriasRouteImport.update({
  id: '/software-para-pizzerias',
  path: '/software-para-pizzerias',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareParaComidasRapidasRoute =
  SoftwareParaComidasRapidasRouteImport.update({
    id: '/software-para-comidas-rapidas',
    path: '/software-para-comidas-rapidas',
    getParentRoute: () => rootRouteImport,
  } as any)
const SoftwareParaCafeteriasRoute = SoftwareParaCafeteriasRouteImport.update({
  id: '/software-para-cafeterias',
  path: '/software-para-cafeterias',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareParaBaresRoute = SoftwareParaBaresRouteImport.update({
  id: '/software-para-bares',
  path: '/software-para-bares',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaPosRestaurantesRoute = SistemaPosRestaurantesRouteImport.update({
  id: '/sistema-pos-restaurantes',
  path: '/sistema-pos-restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuDigitalQrRoute = MenuDigitalQrRouteImport.update({
  id: '/menu-digital-qr',
  path: '/menu-digital-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRestaurantesRoute = InventarioRestaurantesRouteImport.update({
  id: '/inventario-restaurantes',
  path: '/inventario-restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const FidelizacionRestaurantesRoute =
  FidelizacionRestaurantesRouteImport.update({
    id: '/fidelizacion-restaurantes',
    path: '/fidelizacion-restaurantes',
    getParentRoute: () => rootRouteImport,
  } as any)
const FacturacionElectronicaRestaurantesRoute =
  FacturacionElectronicaRestaurantesRouteImport.update({
    id: '/facturacion-electronica-restaurantes',
    path: '/facturacion-electronica-restaurantes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlternativaOlaclickRoute = AlternativaOlaclickRouteImport.update({
  id: '/alternativa-olaclick',
  path: '/alternativa-olaclick',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIndexRoute = RestaurantesIndexRouteImport.update({
  id: '/restaurantes/',
  path: '/restaurantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioIndexRoute = DirectorioIndexRouteImport.update({
  id: '/directorio/',
  path: '/directorio/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsRestaurantesDotxmlRoute =
  SitemapsRestaurantesDotxmlRouteImport.update({
    id: '/sitemaps/restaurantes.xml',
    path: '/sitemaps/restaurantes.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapsPaginasDotxmlRoute = SitemapsPaginasDotxmlRouteImport.update({
  id: '/sitemaps/paginas.xml',
  path: '/sitemaps/paginas.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsDirectorioDotxmlRoute =
  SitemapsDirectorioDotxmlRouteImport.update({
    id: '/sitemaps/directorio.xml',
    path: '/sitemaps/directorio.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantesCiudadIndexRoute = RestaurantesCiudadIndexRouteImport.update({
  id: '/restaurantes/$ciudad/',
  path: '/restaurantes/$ciudad/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioCiudadIndexRoute = DirectorioCiudadIndexRouteImport.update({
  id: '/directorio/$ciudad/',
  path: '/directorio/$ciudad/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesCiudadSlugRoute = RestaurantesCiudadSlugRouteImport.update({
  id: '/restaurantes/$ciudad/$slug',
  path: '/restaurantes/$ciudad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioCiudadCategoriaRoute =
  DirectorioCiudadCategoriaRouteImport.update({
    id: '/directorio/$ciudad/$categoria',
    path: '/directorio/$ciudad/$categoria',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alternativa-olaclick': typeof AlternativaOlaclickRoute
  '/facturacion-electronica-restaurantes': typeof FacturacionElectronicaRestaurantesRoute
  '/fidelizacion-restaurantes': typeof FidelizacionRestaurantesRoute
  '/inventario-restaurantes': typeof InventarioRestaurantesRoute
  '/menu-digital-qr': typeof MenuDigitalQrRoute
  '/precios': typeof PreciosRoute
  '/sistema-pos-restaurantes': typeof SistemaPosRestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software-para-bares': typeof SoftwareParaBaresRoute
  '/software-para-cafeterias': typeof SoftwareParaCafeteriasRoute
  '/software-para-comidas-rapidas': typeof SoftwareParaComidasRapidasRoute
  '/software-para-pizzerias': typeof SoftwareParaPizzeriasRoute
  '/software-restaurantes-cucuta': typeof SoftwareRestaurantesCucutaRoute
  '/soporte': typeof SoporteRoute
  '/support': typeof SupportRoute
  '/sitemaps/directorio.xml': typeof SitemapsDirectorioDotxmlRoute
  '/sitemaps/paginas.xml': typeof SitemapsPaginasDotxmlRoute
  '/sitemaps/restaurantes.xml': typeof SitemapsRestaurantesDotxmlRoute
  '/directorio/': typeof DirectorioIndexRoute
  '/restaurantes/': typeof RestaurantesIndexRoute
  '/directorio/$ciudad/$categoria': typeof DirectorioCiudadCategoriaRoute
  '/restaurantes/$ciudad/$slug': typeof RestaurantesCiudadSlugRoute
  '/directorio/$ciudad/': typeof DirectorioCiudadIndexRoute
  '/restaurantes/$ciudad/': typeof RestaurantesCiudadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alternativa-olaclick': typeof AlternativaOlaclickRoute
  '/facturacion-electronica-restaurantes': typeof FacturacionElectronicaRestaurantesRoute
  '/fidelizacion-restaurantes': typeof FidelizacionRestaurantesRoute
  '/inventario-restaurantes': typeof InventarioRestaurantesRoute
  '/menu-digital-qr': typeof MenuDigitalQrRoute
  '/precios': typeof PreciosRoute
  '/sistema-pos-restaurantes': typeof SistemaPosRestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software-para-bares': typeof SoftwareParaBaresRoute
  '/software-para-cafeterias': typeof SoftwareParaCafeteriasRoute
  '/software-para-comidas-rapidas': typeof SoftwareParaComidasRapidasRoute
  '/software-para-pizzerias': typeof SoftwareParaPizzeriasRoute
  '/software-restaurantes-cucuta': typeof SoftwareRestaurantesCucutaRoute
  '/soporte': typeof SoporteRoute
  '/support': typeof SupportRoute
  '/sitemaps/directorio.xml': typeof SitemapsDirectorioDotxmlRoute
  '/sitemaps/paginas.xml': typeof SitemapsPaginasDotxmlRoute
  '/sitemaps/restaurantes.xml': typeof SitemapsRestaurantesDotxmlRoute
  '/directorio': typeof DirectorioIndexRoute
  '/restaurantes': typeof RestaurantesIndexRoute
  '/directorio/$ciudad/$categoria': typeof DirectorioCiudadCategoriaRoute
  '/restaurantes/$ciudad/$slug': typeof RestaurantesCiudadSlugRoute
  '/directorio/$ciudad': typeof DirectorioCiudadIndexRoute
  '/restaurantes/$ciudad': typeof RestaurantesCiudadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alternativa-olaclick': typeof AlternativaOlaclickRoute
  '/facturacion-electronica-restaurantes': typeof FacturacionElectronicaRestaurantesRoute
  '/fidelizacion-restaurantes': typeof FidelizacionRestaurantesRoute
  '/inventario-restaurantes': typeof InventarioRestaurantesRoute
  '/menu-digital-qr': typeof MenuDigitalQrRoute
  '/precios': typeof PreciosRoute
  '/sistema-pos-restaurantes': typeof SistemaPosRestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/software-para-bares': typeof SoftwareParaBaresRoute
  '/software-para-cafeterias': typeof SoftwareParaCafeteriasRoute
  '/software-para-comidas-rapidas': typeof SoftwareParaComidasRapidasRoute
  '/software-para-pizzerias': typeof SoftwareParaPizzeriasRoute
  '/software-restaurantes-cucuta': typeof SoftwareRestaurantesCucutaRoute
  '/soporte': typeof SoporteRoute
  '/support': typeof SupportRoute
  '/sitemaps/directorio.xml': typeof SitemapsDirectorioDotxmlRoute
  '/sitemaps/paginas.xml': typeof SitemapsPaginasDotxmlRoute
  '/sitemaps/restaurantes.xml': typeof SitemapsRestaurantesDotxmlRoute
  '/directorio/': typeof DirectorioIndexRoute
  '/restaurantes/': typeof RestaurantesIndexRoute
  '/directorio/$ciudad/$categoria': typeof DirectorioCiudadCategoriaRoute
  '/restaurantes/$ciudad/$slug': typeof RestaurantesCiudadSlugRoute
  '/directorio/$ciudad/': typeof DirectorioCiudadIndexRoute
  '/restaurantes/$ciudad/': typeof RestaurantesCiudadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alternativa-olaclick'
    | '/facturacion-electronica-restaurantes'
    | '/fidelizacion-restaurantes'
    | '/inventario-restaurantes'
    | '/menu-digital-qr'
    | '/precios'
    | '/sistema-pos-restaurantes'
    | '/sitemap.xml'
    | '/software-para-bares'
    | '/software-para-cafeterias'
    | '/software-para-comidas-rapidas'
    | '/software-para-pizzerias'
    | '/software-restaurantes-cucuta'
    | '/soporte'
    | '/support'
    | '/sitemaps/directorio.xml'
    | '/sitemaps/paginas.xml'
    | '/sitemaps/restaurantes.xml'
    | '/directorio/'
    | '/restaurantes/'
    | '/directorio/$ciudad/$categoria'
    | '/restaurantes/$ciudad/$slug'
    | '/directorio/$ciudad/'
    | '/restaurantes/$ciudad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alternativa-olaclick'
    | '/facturacion-electronica-restaurantes'
    | '/fidelizacion-restaurantes'
    | '/inventario-restaurantes'
    | '/menu-digital-qr'
    | '/precios'
    | '/sistema-pos-restaurantes'
    | '/sitemap.xml'
    | '/software-para-bares'
    | '/software-para-cafeterias'
    | '/software-para-comidas-rapidas'
    | '/software-para-pizzerias'
    | '/software-restaurantes-cucuta'
    | '/soporte'
    | '/support'
    | '/sitemaps/directorio.xml'
    | '/sitemaps/paginas.xml'
    | '/sitemaps/restaurantes.xml'
    | '/directorio'
    | '/restaurantes'
    | '/directorio/$ciudad/$categoria'
    | '/restaurantes/$ciudad/$slug'
    | '/directorio/$ciudad'
    | '/restaurantes/$ciudad'
  id:
    | '__root__'
    | '/'
    | '/alternativa-olaclick'
    | '/facturacion-electronica-restaurantes'
    | '/fidelizacion-restaurantes'
    | '/inventario-restaurantes'
    | '/menu-digital-qr'
    | '/precios'
    | '/sistema-pos-restaurantes'
    | '/sitemap.xml'
    | '/software-para-bares'
    | '/software-para-cafeterias'
    | '/software-para-comidas-rapidas'
    | '/software-para-pizzerias'
    | '/software-restaurantes-cucuta'
    | '/soporte'
    | '/support'
    | '/sitemaps/directorio.xml'
    | '/sitemaps/paginas.xml'
    | '/sitemaps/restaurantes.xml'
    | '/directorio/'
    | '/restaurantes/'
    | '/directorio/$ciudad/$categoria'
    | '/restaurantes/$ciudad/$slug'
    | '/directorio/$ciudad/'
    | '/restaurantes/$ciudad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlternativaOlaclickRoute: typeof AlternativaOlaclickRoute
  FacturacionElectronicaRestaurantesRoute: typeof FacturacionElectronicaRestaurantesRoute
  FidelizacionRestaurantesRoute: typeof FidelizacionRestaurantesRoute
  InventarioRestaurantesRoute: typeof InventarioRestaurantesRoute
  MenuDigitalQrRoute: typeof MenuDigitalQrRoute
  PreciosRoute: typeof PreciosRoute
  SistemaPosRestaurantesRoute: typeof SistemaPosRestaurantesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoftwareParaBaresRoute: typeof SoftwareParaBaresRoute
  SoftwareParaCafeteriasRoute: typeof SoftwareParaCafeteriasRoute
  SoftwareParaComidasRapidasRoute: typeof SoftwareParaComidasRapidasRoute
  SoftwareParaPizzeriasRoute: typeof SoftwareParaPizzeriasRoute
  SoftwareRestaurantesCucutaRoute: typeof SoftwareRestaurantesCucutaRoute
  SoporteRoute: typeof SoporteRoute
  SupportRoute: typeof SupportRoute
  SitemapsDirectorioDotxmlRoute: typeof SitemapsDirectorioDotxmlRoute
  SitemapsPaginasDotxmlRoute: typeof SitemapsPaginasDotxmlRoute
  SitemapsRestaurantesDotxmlRoute: typeof SitemapsRestaurantesDotxmlRoute
  DirectorioIndexRoute: typeof DirectorioIndexRoute
  RestaurantesIndexRoute: typeof RestaurantesIndexRoute
  DirectorioCiudadCategoriaRoute: typeof DirectorioCiudadCategoriaRoute
  RestaurantesCiudadSlugRoute: typeof RestaurantesCiudadSlugRoute
  DirectorioCiudadIndexRoute: typeof DirectorioCiudadIndexRoute
  RestaurantesCiudadIndexRoute: typeof RestaurantesCiudadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-restaurantes-cucuta': {
      id: '/software-restaurantes-cucuta'
      path: '/software-restaurantes-cucuta'
      fullPath: '/software-restaurantes-cucuta'
      preLoaderRoute: typeof SoftwareRestaurantesCucutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-para-pizzerias': {
      id: '/software-para-pizzerias'
      path: '/software-para-pizzerias'
      fullPath: '/software-para-pizzerias'
      preLoaderRoute: typeof SoftwareParaPizzeriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-para-comidas-rapidas': {
      id: '/software-para-comidas-rapidas'
      path: '/software-para-comidas-rapidas'
      fullPath: '/software-para-comidas-rapidas'
      preLoaderRoute: typeof SoftwareParaComidasRapidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-para-cafeterias': {
      id: '/software-para-cafeterias'
      path: '/software-para-cafeterias'
      fullPath: '/software-para-cafeterias'
      preLoaderRoute: typeof SoftwareParaCafeteriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-para-bares': {
      id: '/software-para-bares'
      path: '/software-para-bares'
      fullPath: '/software-para-bares'
      preLoaderRoute: typeof SoftwareParaBaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema-pos-restaurantes': {
      id: '/sistema-pos-restaurantes'
      path: '/sistema-pos-restaurantes'
      fullPath: '/sistema-pos-restaurantes'
      preLoaderRoute: typeof SistemaPosRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-digital-qr': {
      id: '/menu-digital-qr'
      path: '/menu-digital-qr'
      fullPath: '/menu-digital-qr'
      preLoaderRoute: typeof MenuDigitalQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario-restaurantes': {
      id: '/inventario-restaurantes'
      path: '/inventario-restaurantes'
      fullPath: '/inventario-restaurantes'
      preLoaderRoute: typeof InventarioRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fidelizacion-restaurantes': {
      id: '/fidelizacion-restaurantes'
      path: '/fidelizacion-restaurantes'
      fullPath: '/fidelizacion-restaurantes'
      preLoaderRoute: typeof FidelizacionRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion-electronica-restaurantes': {
      id: '/facturacion-electronica-restaurantes'
      path: '/facturacion-electronica-restaurantes'
      fullPath: '/facturacion-electronica-restaurantes'
      preLoaderRoute: typeof FacturacionElectronicaRestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternativa-olaclick': {
      id: '/alternativa-olaclick'
      path: '/alternativa-olaclick'
      fullPath: '/alternativa-olaclick'
      preLoaderRoute: typeof AlternativaOlaclickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/': {
      id: '/restaurantes/'
      path: '/restaurantes'
      fullPath: '/restaurantes/'
      preLoaderRoute: typeof RestaurantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio/': {
      id: '/directorio/'
      path: '/directorio'
      fullPath: '/directorio/'
      preLoaderRoute: typeof DirectorioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/restaurantes.xml': {
      id: '/sitemaps/restaurantes.xml'
      path: '/sitemaps/restaurantes.xml'
      fullPath: '/sitemaps/restaurantes.xml'
      preLoaderRoute: typeof SitemapsRestaurantesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/paginas.xml': {
      id: '/sitemaps/paginas.xml'
      path: '/sitemaps/paginas.xml'
      fullPath: '/sitemaps/paginas.xml'
      preLoaderRoute: typeof SitemapsPaginasDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/directorio.xml': {
      id: '/sitemaps/directorio.xml'
      path: '/sitemaps/directorio.xml'
      fullPath: '/sitemaps/directorio.xml'
      preLoaderRoute: typeof SitemapsDirectorioDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/$ciudad/': {
      id: '/restaurantes/$ciudad/'
      path: '/restaurantes/$ciudad'
      fullPath: '/restaurantes/$ciudad/'
      preLoaderRoute: typeof RestaurantesCiudadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio/$ciudad/': {
      id: '/directorio/$ciudad/'
      path: '/directorio/$ciudad'
      fullPath: '/directorio/$ciudad/'
      preLoaderRoute: typeof DirectorioCiudadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/$ciudad/$slug': {
      id: '/restaurantes/$ciudad/$slug'
      path: '/restaurantes/$ciudad/$slug'
      fullPath: '/restaurantes/$ciudad/$slug'
      preLoaderRoute: typeof RestaurantesCiudadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio/$ciudad/$categoria': {
      id: '/directorio/$ciudad/$categoria'
      path: '/directorio/$ciudad/$categoria'
      fullPath: '/directorio/$ciudad/$categoria'
      preLoaderRoute: typeof DirectorioCiudadCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlternativaOlaclickRoute: AlternativaOlaclickRoute,
  FacturacionElectronicaRestaurantesRoute:
    FacturacionElectronicaRestaurantesRoute,
  FidelizacionRestaurantesRoute: FidelizacionRestaurantesRoute,
  InventarioRestaurantesRoute: InventarioRestaurantesRoute,
  MenuDigitalQrRoute: MenuDigitalQrRoute,
  PreciosRoute: PreciosRoute,
  SistemaPosRestaurantesRoute: SistemaPosRestaurantesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoftwareParaBaresRoute: SoftwareParaBaresRoute,
  SoftwareParaCafeteriasRoute: SoftwareParaCafeteriasRoute,
  SoftwareParaComidasRapidasRoute: SoftwareParaComidasRapidasRoute,
  SoftwareParaPizzeriasRoute: SoftwareParaPizzeriasRoute,
  SoftwareRestaurantesCucutaRoute: SoftwareRestaurantesCucutaRoute,
  SoporteRoute: SoporteRoute,
  SupportRoute: SupportRoute,
  SitemapsDirectorioDotxmlRoute: SitemapsDirectorioDotxmlRoute,
  SitemapsPaginasDotxmlRoute: SitemapsPaginasDotxmlRoute,
  SitemapsRestaurantesDotxmlRoute: SitemapsRestaurantesDotxmlRoute,
  DirectorioIndexRoute: DirectorioIndexRoute,
  RestaurantesIndexRoute: RestaurantesIndexRoute,
  DirectorioCiudadCategoriaRoute: DirectorioCiudadCategoriaRoute,
  RestaurantesCiudadSlugRoute: RestaurantesCiudadSlugRoute,
  DirectorioCiudadIndexRoute: DirectorioCiudadIndexRoute,
  RestaurantesCiudadIndexRoute: RestaurantesCiudadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
